### ISSUE TITLE
error when rendering novel views

### ISSUE THREAD

**Issue by zhutengjie** [FuxiComputerVision/Nefii#2]
Sorry to bother you again。I run the code successfully to train my dataset. However, I met the error when runing the "render.py"
The error is 
Traceback (most recent call last):
  File "/data/cz/Nefii-main/code/scripts/render.py", line 498, in <module>
    trainrunner.run()
  File "/data/cz/Nefii-main/code/scripts/render.py", line 450, in run
    self.basic_vis(self.test_dataloader)
  File "/data/cz/Nefii-main/code/scripts/render.py", line 311, in basic_vis
    out = self.model(s)
  File "/home/cz/.conda/envs/nefii/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cz/.conda/envs/nefii/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.gather(outputs, self.output_device)
  File "/home/cz/.conda/envs/nefii/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 181, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/cz/.conda/envs/nefii/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 78, in gather
    res = gather_map(outputs)
  File "/home/cz/.conda/envs/nefii/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 69, in gather_map
    return type(out)((k, gather_map([d[k] for d in outputs]))
  File "/home/cz/.conda/envs/nefii/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 69, in <genexpr>
    return type(out)((k, gather_map([d[k] for d in outputs]))
  File "/home/cz/.conda/envs/nefii/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/cz/.conda/envs/nefii/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 56, in forward
    assert all(i.device.type != 'cpu' for i in inputs), (
  File "/home/cz/.conda/envs/nefii/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 56, in <genexpr>
    assert all(i.device.type != 'cpu' for i in inputs), (
AttributeError: 'NoneType' object has no attribute 'device'

**Comment by Skatasi** [comment]
HI. 
You don't define which GPU you use. 
It can be defined by using CUDA_VISIBLE_DEVICES in script file or device_ids in torch.nn.Dataparallel like below.
 `self.model = torch.nn.DataParallel(self.model, device_ids=[0])`

**Comment by zhutengjie** [comment]
Thanks, problem was solved
